### ISSUE TITLE
Simulation-based learning

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#15]

**Comment by gao-ti** [comment]
R. I. A. Ambion, R. S. C. De Leon, A. P. A. R. Mendoza and R. M. Navarro, "The Utilization of the Feynman Technique in Paired Team Teaching Towards Enhancing Grade 10 ANHS Students’ Academic Achievement in Science," 2020 IEEE Integrated STEM Education Conference (ISEC), 2020, pp. 1-3, doi: 10.1109/ISEC49744.2020.9397848.

**Comment by gao-ti** [comment]
https://journals.sagepub.com/doi/10.3102/0034654320933544




@article{doi:10.3102/0034654320933544,
author = {Olga Chernikova and Nicole Heitzmann and Matthias Stadler and Doris Holzberger and Tina Seidel and Frank Fischer},
title ={Simulation-Based Learning in Higher Education: A Meta-Analysis},
journal = {Review of Educational Research},
volume = {90},
number = {4},
pages = {499-541},
year = {2020},
doi = {10.3102/0034654320933544},

URL = { 
        https://doi.org/10.3102/0034654320933544
    
},
eprint = { 
        https://doi.org/10.3102/0034654320933544
    
}
,
    abstract = { Simulation-based learning offers a wide range of opportunities to practice complex skills in higher education and to implement different types of scaffolding to facilitate effective learning. This meta-analysis includes 145 empirical studies and investigates the effectiveness of different scaffolding types and technology in simulation-based learning environments to facilitate complex skills. The simulations had a large positive overall effect: g = 0.85, SE = 0.08; CIs [0.69, 1.02]. Technology use and scaffolding had positive effects on learning. Learners with high prior knowledge benefited more from reflection phases; learners with low prior knowledge learned better when supported by examples. Findings were robust across different higher education domains (e.g., medical and teacher education, management). We conclude that (1) simulations are among the most effective means to facilitate learning of complex skills across domains and (2) different scaffolding types can facilitate simulation-based learning during different phases of the development of knowledge and skills. }
}

**Comment by gao-ti** [comment]
simulation can be viewed as a simplified version of practice and be used to engage novices in practices that are more or less proximal to the practices of a profession

**Comment by gao-ti** [comment]
The operational definition of simulation includes interaction with a real or virtual object, device, or person and the opportunity to alter the flow of this interaction with the decisions and actions made by learners ([Heitzmann et al., 2019](https://journals.sagepub.com/doi/10.3102/0034654320933544#bibr96-0034654320933544)). Thus, all types of interaction, from role plays and standardized patients to highly immersive interactions with virtual objects, can be considered simulations.
The operational definition of simulation also implies that there is critical thinking and a kind of problem solving that is present during learning and learners take an active role in the skill development processes. Simulations have many features to address the complexity of real-world situations ([Davidsson & Verhagen, 2017](https://journals.sagepub.com/doi/10.3102/0034654320933544#bibr62-0034654320933544)); for example, they can involve technology aids to better resemble reality or to provide more practice or learning opportunities. However, the idea of simulation tends to focus on the reconstruction of realistic situations and the genuine interactions that participants can participate in. According to [Grossman et al. (2009)](https://journals.sagepub.com/doi/10.3102/0034654320933544#bibr84-0034654320933544), simulation can be viewed as a simplified version of practice and be used to engage novices in practices that are more or less proximal to the practices of a profession. Therefore, it seems reasonable to additionally focus on the duration of simulation and authenticity in order to determine how realistic the learning environment was and how long the learners were exposed to it.

**Comment by gao-ti** [comment]
Simulation Type
Simulation-based learning had greater effects when presented in the form of live simulations with real patients (g = 2.27, SE = 1.04, N = 3, medical education only), followed by hybrid simulations, where several simulation types were used during learning phases (g = 1.56, SE = 0.17, N = 13). In medical education, mannequins were also highly effective (g = 0.96, SE = 0.11, N = 30). Role plays and using virtual objects had moderate effects on learning (g = 0.63, SE = 0.12, N = 26, and g = 0.75, SE = 0.09, N = 45), and simulations based on documents, although often highly resembling actual tasks (X-rays of patients, students’ homework) were the least effective (g = 0.31, SE = 0.15, N = 15).

**Comment by gao-ti** [comment]
### another papper

https://journals.sagepub.com/doi/10.3102/0034654320933544#body-ref-bibr119-0034654320933544

**Comment by kushal-ti** [comment]
this is all about simulation based learning not Feynman
