### ISSUE TITLE
Mnemonic system research for the table

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#17]

**Comment by gao-ti** [comment]
[The effects of mnemonic instruction and list length on serial learning and retention](https://link.springer.com/content/pdf/10.3758/BF03336474.pdf)

**Comment by arsen-ti** [comment]
Proof that mnemonic images help with memorizing words
link:  http://psychnet.wustl.edu/memory/wp-content/uploads/2018/04/Roediger-1980_JEPHLM.pdf
![memory2](https://user-images.githubusercontent.com/110445289/190077843-1bc35cc7-073c-4d48-a104-1913bc849a57.PNG)

**Comment by arsen-ti** [comment]
Acronyms can help with memorizing words in sequence when applicable
link:  http://www.adamlputnam.com/uploads/8/3/5/6/83563830/putnam_2015.pdf
![memory3](https://user-images.githubusercontent.com/110445289/190081845-4b723c0e-7048-4ed1-b4a4-08ca06bf0543.PNG)

Mnemonics are not always helpful, some material is not compatible with mnemonics
link: https://sci-hub.se/https://doi.org/10.1037/0022-0663.80.4.554
![memory4](https://user-images.githubusercontent.com/110445289/190083566-d562df71-9fde-4945-a3bf-d6f7784be58b.PNG)

**Comment by arsen-ti** [comment]
Mnemonics are not widely used in education institutions
link: http://www.adamlputnam.com/uploads/8/3/5/6/83563830/putnam_2015.pdf
![memory5](https://user-images.githubusercontent.com/110445289/190118238-2c31696b-2c40-4960-b5b2-05142a07ccc5.PNG)
