### ISSUE TITLE
Research recall-based evaluation

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#18]
<html>
<body>

Kliegl, R., Smith, J., & Baltes, P. B. (1989). Testing-the-limits and the study of adult age differences in cognitive plasticity of a mnemonic skill. Developmental Psychology, 25(2), 247.
 

<br class="Apple-interchange-newline">
</body>
</html>

https://publishup.uni-potsdam.de/opus4-ubp/frontdoor/deliver/index/docId/3853/file/kliegl_1989_2.pdf

cognitive plasticity

**We have distinguished, for example, between three levels of information about performance and latent potential: baseline performance, baseline reserve capacity, and developmental reserve capacity. Baseline performance refers to what individuals can do on a given task under standardized conditions of assessment. Baseline reserve capacity is what individuals are capable of performing if the conditions of assessment are optimized without any effort aimed at altering the cognitive and motivational repertoire available to a person. It is a measure of current maximum performance potential or plasticity. Developmental reserve capacity, finally, involves the assessment of performance following interventions or experiences that are aimed at optimizing an individual's cognitive and motivational potential or reserves.**

### Evaluate by recall tests

**Participants were scheduled to participate in a maximum of 26 individual training and 6 standard test sessions (2 pretests and 4 posttests) lasting about 90 min each. The full set of 26 training sessions was implemented only if subjects did not reach a criterion of 80% correct serial recall with the maximum number of locations and items (40) under self-paced presentation.**

**Comment by gao-ti** [comment]
https://docs.google.com/document/d/1J-U-7z71X3UmS5NJ3-pb8tSfWGd955b_J1Y8KYaYiN4/edit#

**Comment by arsen-ti** [comment]
Alright, from ITD AF.6 of the doc -> https://docs.google.com/document/d/1J-U-7z71X3UmS5NJ3-pb8tSfWGd955b_J1Y8KYaYiN4/edit#
I gathered that they evaluate students by:

by whether or not the exercise was finished
aggregation of events (example: how many exercises were finished)
non-event data like how many chapters were prescribes by coachbot

**Comment by gao-ti** [comment]
@arsen-ti 
Basically,

They 
1. create goals for the students
2. put rewards for completion of the goals
3. enable achievements based on the completion of rewards and goals


![image](https://user-images.githubusercontent.com/110180090/190335951-32468ce0-9308-47c2-8fdb-ae43a89ff037.png)

**Comment by gao-ti** [comment]
@arsen-ti @davidfortuoso-ti 

Andy evaluates students based on the completion of goals
But where do such goals come from?

**Comment by arsen-ti** [comment]
Goal is created by choosing from a set of Goal Templates & fill config values
Goal = Goal Template + [Configuration]

Goal Templates that will be supported in the v1:

- EXERCISE_SUCCESSFULLY_COMPLETED. Additional dimensions from the event payload:

Score
Attempt number
Hints used or not
Difficulty level of exercise

- CHAPTER_SUCCESSFULLY_COMPLETED. Additional dimensions from the event payload:

Score
Attempt number
Hints used or not
Difficulty level of chapter

- TEST_SUCCESSFULLY_COMPLETED. Additional dimensions from the event payload:

Score
Attempt number
Hints used or not
Difficulty level of test

- N number of EXERCISE_SUCCESSFULLY_COMPLETED this day / week / month

- N number of CHAPTER_SUCCESSFULLY_COMPLETED this day / week / month

- N number of TEST_SUCCESSFULLY_COMPLETED this day / week / month

- LEADERBOARD_TOP_N_RANK (more details in [IF LB.8](https://docs.google.com/document/d/1J-U-7z71X3UmS5NJ3-pb8tSfWGd955b_J1Y8KYaYiN4/edit#heading=h.sbp3jpwg21o0)). Dimensions from the event payload:
Leaderboard ID
Rank

**Comment by gao-ti** [comment]
@kushal-ti We know how Andy's app does evaluation.

@arsen-ti @davidfortuoso-ti 
Let us now design a way to evaluate as well.
We can reuse Andy's idea of goal templates - goals - rewards - achievements

Let us fill in the 6 pager now as well

**Comment by davidfortuoso-ti** [comment]
@gao-ti Diagram about evaluation/rewards for our product

[https://drive.google.com/file/d/1wcNNbj49aF-3uOn2-3WQSu-LQLESy3dl/view?usp=sharing](https://drive.google.com/file/d/1wcNNbj49aF-3uOn2-3WQSu-LQLESy3dl/view?usp=sharing)

**Comment by gao-ti** [comment]
https://scholarspace.manoa.hawaii.edu/server/api/core/bitstreams/da5455f7-99a3-4f17-a57f-1a0204eca723/content

**Comment by gao-ti** [comment]
@kushal-ti good to be closed?
