### ISSUE TITLE
Find out how Andy's school evaluates its students

### ISSUE THREAD

**Issue by arsen-ti** [trilogy-group/memorization-app#19]
From this doc that they have -> https://docs.google.com/document/d/1J-U-7z71X3UmS5NJ3-pb8tSfWGd955b_J1Y8KYaYiN4/edit#
at ITD AF.6
I gathered that they evaluate students by:
1) by whether or not the exercise was finished
2)  Aggregation of events (example: how many exercises were finished)
3) non-event data like how many chapters were prescribes by coachbot?

**Comment by gao-ti** [comment]
Mentioned in #18 
https://github.com/trilogy-group/memorization-app/issues/18#issuecomment-1247671528

@kushal-ti good to be closed?
