### ISSUE TITLE
Evaluation in Tik-Tok approach

### ISSUE THREAD

**Issue by arsen-ti** [trilogy-group/memorization-app#20]
Tik-Tok approach will allow students to share mnemonic images, acronyms and videos that help with memorizing stuff. We need a way to evaluate whether this apporach is helpful at all or not.

**Comment by arsen-ti** [comment]
The way I see it, we're going to get evaluation methods - exercises and tests from Alpha school. We can see whether or not mnemonics and videos are useful by comparing the results of tests between those who use Tik-Tok approach and those who don't.

![Image](https://user-images.githubusercontent.com/110445289/190369531-78488203-31a3-4075-b8da-0a92f52cc32f.PNG)

**Comment by kushal-ti** [comment]
the idea seems a bit half baked, but overall i think this can work, closing the issue
