### ISSUE TITLE
MemoryTok: research, design, and demo

### ISSUE THREAD

**Issue by arsen-ti** [trilogy-group/memorization-app#22]
- [ ] play around dl models see what we can generate with **Designed Experiments**
- [ ]

**Comment by davidfortuoso-ti** [comment]
Any ideas for this? @gao-ti @arsen-ti @kushal-ti ?

**Comment by arsen-ti** [comment]
I was trying to clone memrise, because it's more useful as a reference. I was looking at this repo -> https://github.com/sustained/ascension
I have an idea of how MemoryTok would look:


![Image](https://user-images.githubusercontent.com/110445289/190603798-3ee522c8-5414-4b05-9b5c-08ab9ffe8a8c.PNG)


![Image](https://user-images.githubusercontent.com/110445289/190603844-dbf4d199-8c4c-4723-9bf9-991100e34581.PNG)

**Comment by gao-ti** [comment]
@kushal-ti 
Does the design look good to you?

Where do you think @arsen-ti can start with the memrise-like design?

**Comment by gao-ti** [comment]
https://workflowy.com/s/research/USnUsdmdAMZltW05


![image](https://user-images.githubusercontent.com/110180090/190862047-2a959ded-9ccf-434c-9f77-0e3a5383daf7.png)

**Comment by gao-ti** [comment]
https://github.com/mnemosyne-proj/mnemosyne
https://mnemosyne-proj.org/features

This is an open source competitor
- creation, but no sharing
- spaced repetition
- can hold on server, no security implemented

**Comment by gao-ti** [comment]
## ProxiTok: We shouldn't reuse its frontend

- written in Php
- very ugly

https://github.com/pablouser1/ProxiTok

**Comment by gao-ti** [comment]
### User flow design


https://www.canva.com/design/DAFM2CriaXI/DgaaHuM_IpFDW1a4NISpdw/edit?utm_content=DAFM2CriaXI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by kushal-ti** [comment]
closing this in favour of more granular issues
