### ISSUE TITLE
Create diagram of memorization flow

### ISSUE THREAD

**Issue by davidfortuoso-ti** [trilogy-group/memorization-app#25]

**Comment by davidfortuoso-ti** [comment]
https://drive.google.com/file/d/16fllgdMJgtUzMx1wrHcVIKamJCoefR47/view?usp=sharing

**Comment by gao-ti** [comment]
This is the final version we had

https://www.canva.com/design/DAFMYTRl3rw/_ysHeP4f3x62ecHWsCDnPQ/edit?utm_content=DAFMYTRl3rw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

closed due to completion of #24
