### ISSUE TITLE
MemoryCraft: gamification platform for memory palace research

### ISSUE THREAD

**Issue by davidfortuoso-ti** [trilogy-group/memorization-app#26]
Research available gamification platforms (minecraft, roblox, etc) their pros and cons and the costs.
Goal: customizable memoryOS

- [ ] Minecraft
- [ ] Roblox
- [ ] RPG Maker
- [ ] The sandbox
- [ ] CoSpace Edu
- [ ] Unity

**Comment by gao-ti** [comment]
### RPG Maker

https://www.rpgmakerweb.com/
http://openrpgmaker.sourceforge.net/

**Comment by gao-ti** [comment]
## Roblox Studio

https://www.roblox.com/create

**Comment by gao-ti** [comment]
### A list of virtual memory palaces from art of memory


https://artofmemory.com/blog/virtual-memory-palaces/

**Comment by gao-ti** [comment]
## CoSpaces Edu

They are VR-based, but they have student-created content

https://blog.cospaces.io/creating-a-virtual-memory-palace-with-cospaces-edu-a91603e87607
