### ISSUE TITLE
Content Generation Experiment (MemoryTok)

### ISSUE THREAD

**Issue by arsen-ti** [trilogy-group/memorization-app#38]
I'll try creating mnemonics images using Stable Diffusion. Let us see its the capabilitites and limitation.
I will use this link -> https://beta.dreamstudio.ai/dream

Limitations:
1) Sometimes it fails to draw what the prompt says.
2) Writes jibberish instead of meaningful text in the generated image
3) It may take several iterations until you get a satisfying image

Prompt Fails:
1) Can't draw Pugna from Dota 2
![Image](https://user-images.githubusercontent.com/110445289/191201933-e01ef603-7c2a-4359-b993-7c6fa4baa89f.PNG)

2) Can't draw a monkey holding a sign saying "Hello"

![Image](https://user-images.githubusercontent.com/110445289/191203487-7701f927-0e2f-4f6a-acda-e620be3b63b5.PNG)

3) "Two dogs dressed like Santa fighting each other using swords on a pirate ship"

![Image](https://user-images.githubusercontent.com/110445289/191215236-de6aff9c-b547-4128-b41b-a7c3e315ea20.PNG)

Examples:
1) "A monk talking to a skeleton in a drinking bar". It took several iterations to get a decent image among 9 generated. Generated skeletons often have missing bones. 

![Image](https://user-images.githubusercontent.com/110445289/191205613-117b4722-09f0-4bc0-a901-237faca859e7.PNG)

Sometimes faces can look disfigured. I can no longer use Dream Studio, because I've used it too much. But, trust me, faces can be distracting.

**Comment by arsen-ti** [comment]
Use OpenAI’s GPT-3 models to generate acrostics and peg lists
I will use this link -> https://beta.openai.com/playground
I don't fine-tune it, the model is called "text-davinci-002"

Limitations:

**Comment by arsen-ti** [comment]
I struggle with creating acrostics at the moment

**Comment by gao-ti** [comment]
### openAI
![image](https://user-images.githubusercontent.com/110180090/191279090-7901b3be-e6c1-4278-bdec-e59c2dc80f13.png)

**Comment by arsen-ti** [comment]
I picked biology as a subject in the experiment, because there's a lot of terms to memorize. I tried to memorize the word 'cell' by imagining a human cell inside of prison cell. So, I put the prompt and didn't get a good image (I imagined a huge human cell like those you see in Google search behind prison bars).

![Image](https://user-images.githubusercontent.com/110445289/191413316-f18f7d92-ac14-4b90-bb05-8ee026dcb336.PNG)

Next, I tried to memorize the word 'organelle' by imagining an organ (instrument) inside a biological cell. Again, results are not good. Nothing in the results resembles organ.


![Image](https://user-images.githubusercontent.com/110445289/191416097-84102a52-ad79-4ee2-af5b-b51e5bccaa6e.PNG)

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/191437073-b2080286-c903-443a-ada7-7d27b32c408e.png)

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/191438422-af2b3365-84a9-46e6-ba23-f61dd4ff3d76.png)

**Comment by kushal-ti** [comment]
GPT-3 in general seems to be reliable, @davidfortuoso-ti we can use this in the content generation experiments

**Comment by kushal-ti** [comment]
closed in favour of #44
