### ISSUE TITLE
6-Pager: Update Problem Definition Table

### ISSUE THREAD

**Issue by davidfortuoso-ti** [trilogy-group/memorization-app#4]
- [x] Customer Niche
- [x] Business Problem
- [x] Why to solve it 
- [x] Customer Constraints
- [ ] Product Solution
- [x] Approach

**Comment by kushal-ti** [comment]
You should be able to update the existing problem definition table, as soon as it's done, add a comment and tag me for review

**Comment by davidfortuoso-ti** [comment]
Updated
