### ISSUE TITLE
Cleanup necessary files in default branch

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#42]

**Comment by kushal-ti** [comment]
since we're doing a full frontend rewrite, i think this shouldn't matter anymore, we'll move all existing code to a folder named deprecate and start anew, agreed @gao-ti @arsen-ti ?

**Comment by arsen-ti** [comment]
@kushal-ti that depends on whether we're going to change UI drastically or not

**Comment by gao-ti** [comment]
Closed due to frontend rewrite.

**Comment by kushal-ti** [comment]
@arsen-ti i think we all agree that a full rewrite is needed, even if eventually end up using a interface similar to flashcards, the current code with vanilla js is not feasible in the long term given how dynamic our website needs to be
