### ISSUE TITLE
Frontend: review existing open-source tik-tok options

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#48]
We plan to

- [x] openChakra then modify the code
- [x] Modify an existing Tiktok clone

**Comment by gao-ti** [comment]
source code
https://github.com/napthedev/toptop-clone

demo
https://toptop-clone.vercel.app/

**Comment by gao-ti** [comment]
Now the toktok works

![image](https://user-images.githubusercontent.com/110180090/192308229-9b4b0c87-e8d1-44f2-b4cc-fcba3a3d94b8.png)

**Comment by gao-ti** [comment]
code pushed at
https://github.com/trilogy-group/memorization-app/tree/master

**Comment by gao-ti** [comment]
Overlapped with below issues @kushal-ti 

Please review and let's see if we can close them
- [ ] #49 
- [ ] #51
- [ ] #54 
- [ ] #46

**Comment by kushal-ti** [comment]
can definitely close this isssue, will take a look at the others listed above
