### ISSUE TITLE
Frontend Rewrite: User feeds

### ISSUE THREAD

**Issue by kushal-ti** [trilogy-group/memorization-app#49]
- [x] Scrolling/Swiping Feeds with Mnemonic Content
- [x] Display Question/Answer alongside mnemonic to be visualized

**Comment by kushal-ti** [comment]
@gao-ti can you link the PR which manages this or is it already merged into the main branch? if so, can you post a video recording how the user feeds are working

**Comment by gao-ti** [comment]
@kushal-ti The features here are addressed in the previous commits in the master branch, implemented by the open source comminity

https://github.com/trilogy-group/memorization-app/commits/master

**Comment by kushal-ti** [comment]
@gao-ti this is mostly done, just manage the part with fullscreen videos and we can close this

**Comment by gao-ti** [comment]
Blocked due to fullscreen video scroll not working. Now it scrolls through the middle between two cards

Requested help from Vinayak and Bilal.

**Comment by gao-ti** [comment]
https://github.com/trilogy-group/memorization-app/pull/143

Enable quiz and post appear in the feed at the same time
