### ISSUE TITLE
Review memorization techniques hinted by Vicky

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#5]
[https://www.youtube.com/watch?v=rhgwIhB58PA](https://www.youtube.com/watch?v=rhgwIhB58PA)
[https://www.youtube.com/watch?v=hfi0OiMuXcM](https://www.youtube.com/watch?v=hfi0OiMuXcM)
[https://www.youtube.com/watch?v=s6OmqXCsYt8](https://www.youtube.com/watch?v=s6OmqXCsYt8)
[https://www.youtube.com/watch?v=mI96Ph-yHcA](https://www.youtube.com/watch?v=mI96Ph-yHcA)
[https://www.youtube.com/watch?v=U6PoUg7jXsA](https://www.youtube.com/watch?v=U6PoUg7jXsA)
[https://www.youtube.com/results?search_query=memory+competition+training](https://www.youtube.com/results?search_query=memory+competition+training)

**Comment by davidfortuoso-ti** [comment]
[https://www.youtube.com/watch?v=rhgwIhB58PA](https://www.youtube.com/watch?v=rhgwIhB58PA)

https://www.youtube.com/watch?v=rhgwIhB58PA
Everyone has a preferred way of learning (that’s what people think):
   - Visual
   - Auditory
   - Reading/writing
   - Kinesthetic

They do an experiment where they use different memorization styles from what people think they are good at.


[https://www.youtube.com/watch?v=hfi0OiMuXcM](https://www.youtube.com/watch?v=hfi0OiMuXcM)

**Comment by arsen-ti** [comment]
Welp, it was not helpful at all. What I got from these videos:
1) Memorization technique -> create a story ( which is basically a sequence mnemotic images). Already knew that
2) Memory palace. Already knew that
3) Some memory athletes adviced that to memorize you need to get rid of distractions, you need to dwell on it constantly and understand it (not memorize it), try to write what you memorized (active recall) 
4) Those memory athletes are a bunch of shills for their courses

**Comment by kushal-ti** [comment]
closing this as done
