### ISSUE TITLE
Frontend Rewrite: Tags/Topic selection

### ISSUE THREAD

**Issue by kushal-ti** [trilogy-group/memorization-app#50]
There needs to be a way for users to select the specific topics/sections which they have studied/want to memorize better. 

Implementation details are left to the assignee

**Comment by gao-ti** [comment]
This comes before having an api to track the students' progress.

Thus I plan to give higher priority to this issue

**Comment by gao-ti** [comment]
https://github.com/trilogy-group/memorization-app/pull/59

**Comment by gao-ti** [comment]
Single tag search supported

![image](https://user-images.githubusercontent.com/110180090/192762290-bc9a82f4-772b-448b-ae82-7b9f0655be5b.png)

**Comment by gao-ti** [comment]
@kushal-ti need some help with one query

[This line](https://github.com/trilogy-group/memorization-app/pull/59/files#diff-9579933ab985f95c6d94d54a6eb3476017c0c4ad58906c942c9ddaf7c6616696R207)
I wrote now searches for the first tag.

I am not sure how to support searching of multiple tags.
e.g., set the condition to select videos where tags include both `#Spanish` and `#Chapter1`

I am moving on to the scoreboard issue.
It is very helpful if you have some idea on this one

**Comment by gao-ti** [comment]
PR #59 merged.
TODO:
#67

**Comment by gao-ti** [comment]
#67 supported now
