### ISSUE TITLE
Frontend Rewrite: User profile and homepage

### ISSUE THREAD

**Issue by kushal-ti** [trilogy-group/memorization-app#54]
- [ ] User profile with the following features
     - [ ] Completed concepts/sections
     - [ ] In-progress sections
     - [ ] Next recommended 
     - [x] Students total points
     - [ ] Profile with strengths and weaknesses (eg. good at us history, bad at world history)
- [ ] Home page with the following
     - [x] Weekly leaderboard
     - [ ] Most popular posts of day, week, month, etc.
     - [ ] Upcoming games/quizzes where students can win points/rewards

**Comment by gao-ti** [comment]
#55 will include `Weekly leaderboard`

**Comment by gao-ti** [comment]
We need to sort out
- what is needed for this week's demo
- what can be added as features in the following weeks

**Comment by gao-ti** [comment]
- Completed concepts/sections
- show students total points in profile
- show student's total points in leaderboard

I'll do this tomorrow

**Comment by gao-ti** [comment]
- [x] show students total points in profile
- [x] show student's total points in leaderboard

https://github.com/trilogy-group/memorization-app/pull/75

**Comment by gao-ti** [comment]
The issue is broken down into smaller ones.

Details #78

**Comment by gao-ti** [comment]
Closed due to large changes in the frontend design

https://github.com/trilogy-group/memorization-app/issues/116
