### ISSUE TITLE
Frontend Rewrite: Rewards and Progress

### ISSUE THREAD

**Issue by kushal-ti** [trilogy-group/memorization-app#55]
This will be a part of the students profile itself and hence should be picked up only when #54 is completed
- [x] Total number of points users have won so far
- [ ] Accomplishments/badges that have been won so far
- [ ] Daily Streak status
- [ ] Scores across quizzes/games so far

**Comment by gao-ti** [comment]
And a score board WIP

**Comment by gao-ti** [comment]
PR available #63 
ready for review

**Comment by gao-ti** [comment]
- Accomplishments/badges that have been won so far
- Daily Streak status

@kushal-ti those two are not urgent for this week's demo right?

- Scores across quizzes/games so far
pending for quizzes to be implemented

**Comment by kushal-ti** [comment]
i suppose they're not, but i don't want to open another issue for those, keeping this open and in todo for now, if we get the time, we'll implement these as well

**Comment by gao-ti** [comment]
PR #63 merged

#65 #66 new TODOs

**Comment by gao-ti** [comment]
closed due to outdated

**Comment by gao-ti** [comment]
closed due to outdated
