### ISSUE TITLE
Research: nextjs server arbitrary code execution

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#62]
- [x] Capable of Running on startup
- [x] Capable of Running Arbitrary code on the backend
- [x] Capable of Being Deployed on Lambdas using [serverless-next.js](https://github.com/serverless-nextjs/serverless-next.js)
- [x] Capable of generating static website during build time
- [ ] 

https://github.com/vercel/next.js/discussions/15341

**Comment by gao-ti** [comment]
https://nextjs.org/docs/advanced-features/middleware

```
Middleware allows you to run code before a request is completed, then based on the incoming request, you can modify the response by rewriting, redirecting, adding headers, or setting cookies.
```

**Comment by gao-ti** [comment]
If you have an existing backend, you can still use it with Next.js (this is not a custom server). A custom Next.js server allows you to start a server 100% programmatically in order to use custom server patterns. 

https://nextjs.org/docs/advanced-features/custom-server

https://flaviocopes.com/nextjs-server-client-code/

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/192794123-9835839c-cf52-440d-898d-66844d57f1b9.png)

**Comment by gao-ti** [comment]
Custom server
- can run when server starts
- can use app render

Experiment code here
https://github.com/trilogy-group/memorization-app/tree/custom-server

**Comment by gao-ti** [comment]
How NextJS works under the hood: https://nextjs.org/learn/foundations/how-nextjs-works/client-and-server

**Comment by gao-ti** [comment]
https://blog.logrocket.com/deploying-nextjs-aws-serverless-next-js/


deploy nextjs on serverless

**Comment by gao-ti** [comment]
@kushal-ti I think we have basically reached our conclusion on this issue right?

**Comment by kushal-ti** [comment]
yeah this can be closed
