### ISSUE TITLE
6-Pager: Research

### ISSUE THREAD

**Issue by kushal-ti** [trilogy-group/memorization-app#7]
Add research entries to 6 Pager for the following aspects 
- [x] Different evaluation techniques for memory retention (active recall, testing effect, etc.)

You may add any other topics you can think of for research 
Have tangible results for each research topic. Failing to get any useful information from research is also an acceptable, tangible result

**Comment by davidfortuoso-ti** [comment]
Spaced repetition: [https://medium.com/skilluped/learning-by-spaced-repetition-how-effective-is-it-2654786db073](https://medium.com/skilluped/learning-by-spaced-repetition-how-effective-is-it-2654786db073) 
   - How can we implement it on our product?
      - Different difficulty levels on the palaces. Each level you repeat the same content but are asked for different parts of it (Put items in place, write the name, write the description, etc.)
      - Reminders to repeat levels completed in the past to make sure the student still remembers them.

**Comment by kushal-ti** [comment]
@arsen-ti how would you implement spaced repetition with mnemonics

**Comment by gao-ti** [comment]
Research on recalll based evaluation

https://github.com/trilogy-group/memorization-app/issues/18

**Comment by arsen-ti** [comment]
Spaced repitition is usually paired with flashcards. You have a something you want to memorize, for example, a foreign word on each flashcard. You go through flashcards and each flashcard is designated as either familiar (you know what that word means) or unfamiliar. Unfamiliar flashcards need to be revisited, they have priority over familiar card. You revisit familiar cards every day, then 3 days, then a week. There is an increasing time interval between revisiting familiar cards

![Image](https://user-images.githubusercontent.com/110445289/190580278-be227e37-f80f-4828-b873-385aea8d8dc8.png)

**Comment by arsen-ti** [comment]
@kushal-ti we can't use flashcards, unfortunately. In memrise on each flashcard there is a mnemonic image that helps you remember GRE vocabulary word. At first, you have MCQ to guess what that word means, but when you guess correctly that word becomes familar, then you will have to type out that word (active recall) after a while (spaced repitition)

**Comment by kushal-ti** [comment]
We absolutely can use flashcard like things in the memoryTok thing if it helps
