### ISSUE TITLE
6-Pager: Solution Approach

### ISSUE THREAD

**Issue by kushal-ti** [trilogy-group/memorization-app#9]

**Comment by davidfortuoso-ti** [comment]
[https://docs.google.com/document/d/1nvjjZLp-tyHqi_OiUpmghbWmP8gjnmr-RqzIh33ULGA/edit#heading=h.70y3drmv9lwf](https://docs.google.com/document/d/1nvjjZLp-tyHqi_OiUpmghbWmP8gjnmr-RqzIh33ULGA/edit#heading=h.70y3drmv9lwf)

Describe the 2 solutions we're offering, memorytok and memorycraft

**Comment by arsen-ti** [comment]
I proposed mnemonic system that allows students to create and share mnemonic images and videos. It's called memorytok for now.
